import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ChessController {
    private NewGraphic view;
    private ChessLogic logic;

    public ChessController(){
        ChessLogic logic=new ChessLogic();
        Player player1=new Player("white","white");
        Player player2=new Player("black","black");
        for (PlaceView[] placeViewList:
                view.getPlaceViewList())
            for (PlaceView placeView:
                    placeViewList) {
            placeView.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    PlaceView thePlaceView=(PlaceView) (e.getSource());
                    System.out.println("A");
                   // logic.getValidMoves()
                }
            });
        }
    }

    private static boolean chooseAndPut(String choose,String put,int turn,ChessLogic logic)
    {
        char c11=choose.charAt(0);
        char c12=choose.charAt(1);
        char c21=put.charAt(0);
        char c22=put.charAt(1);
        int i1=0,i2=0,j1=0,j2=0;
        int result11=0,result12=0,result21=0,result22=0;
        if(c11=='a')
        {
            j1=0;
            result12=1;
            if(c12=='1')
            {
                i1=0;
                result11=1;
            }
            if(c12=='2')
            {
                i1=1;
                result11=1;
            }
            if(c12=='3')
            {
                i1=2;
                result11=1;
            }
            if(c12=='4')
            {
                i1=3;
                result11=1;
            }
            if(c12=='5')
            {
                i1=4;
                result11=1;
            }
            if(c12=='6')
            {
                i1=5;
                result11=1;
            }
            if(c12=='7')
            {
                i1=6;
                result11=1;
            }
            if(c12=='8')
            {
                i1=7;
                result11=1;
            }

        }
        if(c11=='b')
        {
            j1=1;
            result12=1;
            if(c12=='1')
            {
                i1=0;
                result11=1;
            }
            if(c12=='2')
            {
                i1=1;
                result11=1;
            }
            if(c12=='3')
            {
                i1=2;
                result11=1;
            }
            if(c12=='4')
            {
                i1=3;
                result11=1;
            }
            if(c12=='5')
            {
                i1=4;
                result11=1;
            }
            if(c12=='6')
            {
                i1=5;
                result11=1;
            }
            if(c12=='7')
            {
                i1=6;
                result11=1;
            }
            if(c12=='8')
            {
                i1=7;
                result11=1;
            }

        }
        if(c11=='c')
        {
            j1=2;
            result12=1;
            if(c12=='1')
            {
                i1=0;
                result11=1;
            }
            if(c12=='2')
            {
                i1=1;
                result11=1;
            }
            if(c12=='3')
            {
                i1=2;
                result11=1;
            }
            if(c12=='4')
            {
                i1=3;
                result11=1;
            }
            if(c12=='5')
            {
                i1=4;
                result11=1;
            }
            if(c12=='6')
            {
                i1=5;
                result11=1;
            }
            if(c12=='7')
            {
                i1=6;
                result11=1;
            }
            if(c12=='8')
            {
                i1=7;
                result11=1;
            }

        }
        if(c11=='d')
        {
            j1=3;
            result12=1;
            if(c12=='1')
            {
                i1=0;
                result11=1;
            }
            if(c12=='2')
            {
                i1=1;
                result11=1;
            }
            if(c12=='3')
            {
                i1=2;
                result11=1;
            }
            if(c12=='4')
            {
                i1=3;
                result11=1;
            }
            if(c12=='5')
            {
                i1=4;
                result11=1;
            }
            if(c12=='6')
            {
                i1=5;
                result11=1;
            }
            if(c12=='7')
            {
                i1=6;
                result11=1;
            }
            if(c12=='8')
            {
                i1=7;
                result11=1;
            }

        }
        if(c11=='e')
        {
            j1=4;
            result12=1;
            if(c12=='1')
            {
                i1=0;
                result11=1;
            }
            if(c12=='2')
            {
                i1=1;
                result11=1;
            }
            if(c12=='3')
            {
                i1=2;
                result11=1;
            }
            if(c12=='4')
            {
                i1=3;
                result11=1;
            }
            if(c12=='5')
            {
                i1=4;
                result11=1;
            }
            if(c12=='6')
            {
                i1=5;
                result11=1;
            }
            if(c12=='7')
            {
                i1=6;
                result11=1;
            }
            if(c12=='8')
            {
                i1=7;
                result11=1;
            }

        }
        if(c11=='f')
        {
            j1=5;
            result12=1;
            if(c12=='1')
            {
                i1=0;
                result11=1;
            }
            if(c12=='2')
            {
                i1=1;
                result11=1;
            }
            if(c12=='3')
            {
                i1=2;
                result11=1;
            }
            if(c12=='4')
            {
                i1=3;
                result11=1;
            }
            if(c12=='5')
            {
                i1=4;
                result11=1;
            }
            if(c12=='6')
            {
                i1=5;
                result11=1;
            }
            if(c12=='7')
            {
                i1=6;
                result11=1;
            }
            if(c12=='8')
            {
                i1=7;
                result11=1;
            }

        }
        if(c11=='g')
        {
            j1=6;
            result12=1;
            if(c12=='1')
            {
                i1=0;
                result11=1;
            }
            if(c12=='2')
            {
                i1=1;
                result11=1;
            }
            if(c12=='3')
            {
                i1=2;
                result11=1;
            }
            if(c12=='4')
            {
                i1=3;
                result11=1;
            }
            if(c12=='5')
            {
                i1=4;
                result11=1;
            }
            if(c12=='6')
            {
                i1=5;
                result11=1;
            }
            if(c12=='7')
            {
                i1=6;
                result11=1;
            }
            if(c12=='8')
            {
                i1=7;
                result11=1;
            }

        }
        if(c11=='h')
        {
            j1=7;
            result12=1;
            if(c12=='1')
            {
                i1=0;
                result11=1;
            }
            if(c12=='2')
            {
                i1=1;
                result11=1;
            }
            if(c12=='3')
            {
                i1=2;
                result11=1;
            }
            if(c12=='4')
            {
                i1=3;
                result11=1;
            }
            if(c12=='5')
            {
                i1=4;
                result11=1;
            }
            if(c12=='6')
            {
                i1=5;
                result11=1;
            }
            if(c12=='7')
            {
                i1=6;
                result11=1;
            }
            if(c12=='8')
            {
                i1=7;
                result11=1;
            }

        }
        if(c21=='a')
        {
            int w;
            j2=0;
            result22=1;
            if(c22=='1')
            {
                i2=0;
                result21=1;
            }
            if(c22=='2')
            {
                i2=1;
                result21=1;
            }
            if(c22=='3')
            {
                i2=2;
                result21=1;
            }
            if(c22=='4')
            {
                i2=3;
                result21=1;
            }
            if(c22=='5')
            {
                i2=4;
                result21=1;
            }
            if(c22=='6')
            {
                i2=5;
                result21=1;
            }
            if(c22=='7')
            {
                i2=6;
                result21=1;
            }
            if(c22=='8')
            {
                i2=7;
                result21=1;
            }

        }
        if(c21=='b')
        {
            int w;
            j2=1;
            result22=1;
            if(c22=='1')
            {
                i2=0;
                result21=1;
            }
            if(c22=='2')
            {
                i2=1;
                result21=1;
            }
            if(c22=='3')
            {
                i2=2;
                result21=1;
            }
            if(c22=='4')
            {
                i2=3;
                result21=1;
            }
            if(c22=='5')
            {
                i2=4;
                result21=1;
            }
            if(c22=='6')
            {
                i2=5;
                result21=1;
            }
            if(c22=='7')
            {
                i2=6;
                result21=1;
            }
            if(c22=='8')
            {
                i2=7;
                result21=1;
            }

        }
        if(c21=='c')
        {
            int w;
            j2=2;
            result22=1;
            if(c22=='1')
            {
                i2=0;
                result21=1;
            }
            if(c22=='2')
            {
                i2=1;
                result21=1;
            }
            if(c22=='3')
            {
                i2=2;
                result21=1;
            }
            if(c22=='4')
            {
                i2=3;
                result21=1;
            }
            if(c22=='5')
            {
                i2=4;
                result21=1;
            }
            if(c22=='6')
            {
                i2=5;
                result21=1;
            }
            if(c22=='7')
            {
                i2=6;
                result21=1;
            }
            if(c22=='8')
            {
                i2=7;
                result21=1;
            }

        }
        if(c21=='d')
        {
            int w;
            j2=3;
            result22=1;
            if(c22=='1')
            {
                i2=0;
                result21=1;
            }
            if(c22=='2')
            {
                i2=1;
                result21=1;
            }
            if(c22=='3')
            {
                i2=2;
                result21=1;
            }
            if(c22=='4')
            {
                i2=3;
                result21=1;
            }
            if(c22=='5')
            {
                i2=4;
                result21=1;
            }
            if(c22=='6')
            {
                i2=5;
                result21=1;
            }
            if(c22=='7')
            {
                i2=6;
                result21=1;
            }
            if(c22=='8')
            {
                i2=7;
                result21=1;
            }

        }
        if(c21=='e')
        {
            int w;
            j2=4;
            result22=1;
            if(c22=='1')
            {
                i2=0;
                result21=1;
            }
            if(c22=='2')
            {
                i2=1;
                result21=1;
            }
            if(c22=='3')
            {
                i2=2;
                result21=1;
            }
            if(c22=='4')
            {
                i2=3;
                result21=1;
            }
            if(c22=='5')
            {
                i2=4;
                result21=1;
            }
            if(c22=='6')
            {
                i2=5;
                result21=1;
            }
            if(c22=='7')
            {
                i2=6;
                result21=1;
            }
            if(c22=='8')
            {
                i2=7;
                result21=1;
            }

        }
        if(c21=='f')
        {
            int w;
            j2=5;
            result22=1;
            if(c22=='1')
            {
                i2=0;
                result21=1;
            }
            if(c22=='2')
            {
                i2=1;
                result21=1;
            }
            if(c22=='3')
            {
                i2=2;
                result21=1;
            }
            if(c22=='4')
            {
                i2=3;
                result21=1;
            }
            if(c22=='5')
            {
                i2=4;
                result21=1;
            }
            if(c22=='6')
            {
                i2=5;
                result21=1;
            }
            if(c22=='7')
            {
                i2=6;
                result21=1;
            }
            if(c22=='8')
            {
                i2=7;
                result21=1;
            }

        }
        if(c21=='g')
        {
            int w;
            j2=6;
            result22=1;
            if(c22=='1')
            {
                i2=0;
                result21=1;
            }
            if(c22=='2')
            {
                i2=1;
                result21=1;
            }
            if(c22=='3')
            {
                i2=2;
                result21=1;
            }
            if(c22=='4')
            {
                i2=3;
                result21=1;
            }
            if(c22=='5')
            {
                i2=4;
                result21=1;
            }
            if(c22=='6')
            {
                i2=5;
                result21=1;
            }
            if(c22=='7')
            {
                i2=6;
                result21=1;
            }
            if(c22=='8')
            {
                i2=7;
                result21=1;
            }

        }
        if(c21=='h')
        {
            int w;
            j2=7;
            result22=1;
            if(c22=='1')
            {
                i2=0;
                result21=1;
            }
            if(c22=='2')
            {
                i2=1;
                result21=1;
            }
            if(c22=='3')
            {
                i2=2;
                result21=1;
            }
            if(c22=='4')
            {
                i2=3;
                result21=1;
            }
            if(c22=='5')
            {
                i2=4;
                result21=1;
            }
            if(c22=='6')
            {
                i2=5;
                result21=1;
            }
            if(c22=='7')
            {
                i2=6;
                result21=1;
            }
            if(c22=='8')
            {
                i2=7;
                result21=1;
            }

        }
        if(result11==0||result12==0||result21==0||result22==0)
        {
            System.out.println("WRONG INPUT.");
        }
        else
        {
            System.out.println("(i1="+i1+"  j1="+j1+"  i2="+i2+"  j2="+j2+")");

            Place choseSquare=logic.getPlace(i1,j1);
            if(choseSquare.getPiece()==null){
                System.out.println("NULL");return false;}
            else
            {
                if((turn%2==1&&choseSquare.getPiece().getColor().equals("white"))||(turn%2==0&&choseSquare.getPiece().getColor().equals("black")))
                    return choseSquare.getPiece().move(j1,i1,j2,i2,logic.getField());
                else return false;
            }

        }


        return false;
    }

}
